meson.build, po/POTFILES, src/DesktopFile.vala, src/DesktopFileOperator.vala, src/FilesView.vala, src/MainWindow.vala, src/WelcomeView.vala
=> Add FilesView

com.github.ryonakano.pinit.yml, src/DesktopFileOperator.vala, src/FilesView.vala, src/MainWindow.vala
=> FilesView: Show app info

data/icons/128/com.github.ryonakano.pinit.svg
Finally I was able to cherry-pick the one commit that adds 128px icon by @hanaral
=> Add 128px icon

data/pinit.appdata.xml.in, meson.build, src/Views/FilesView.vala
=> FilesView: Ellipsize if label texts are too long

po/LINGUAS, po/extra/LINGUAS, po/extra/pt_BR.po, po/pt_BR.po
Hello, this is the Brazilian Portuguese translation. Thanks for the app!
=> Add Brazilian Porguguese translation

src/Backend/DesktopFileOperator.vala, src/MainWindow.vala, src/Views/WelcomeView.vala
=> DesktopFileOperator: Remove create_new

data/meson.build, meson.build, meson_options.txt, src/Application.vala, src/MainWindow.vala, src/StyleSwitcher.vala, src/Views/FilesView.vala
=> Check desktop environment on runtime

data/Application.css, data/pinit.appdata.xml.in, data/pinit.gschema.xml, src/Application.vala, src/CategoryChooser.vala, src/MainWindow.vala, src/Views/EditView.vala
=> Make window resizable

data/pinit.appdata.xml.in, meson.build, po/POTFILES, src/InfoButton.vala, src/Views/EditView.vala
=> EditView: Less strict on file names

po/LINGUAS, po/extra/LINGUAS, po/extra/nl.po, po/nl.po
=> Add Dutch translation

meson.build, src/Application.vala, src/Config.vala.in, src/MainWindow.vala, src/Views/WelcomeView.vala
=> Use consts if possible

src/Views/EditView.vala
=> EditView: Support loading .ico

com.github.ryonakano.pinit.yml
=> Revert "Flatpak: Only allow access to the desktop files dir"

.gitignore, .vscode/launch.json, meson.build, meson_options.txt
Thanks to https://youtu.be/3yyDdA5IMLI for these info!
=> Set up debugging environment

src/Backend/DesktopFile.vala, src/Backend/DesktopFileOperator.vala, src/Views/EditView.vala
=> Add StartupWMClass entry

src/Application.vala, src/Backend/DesktopFile.vala, src/Backend/DesktopFileOperator.vala, src/CategoryChooser.vala, src/MainWindow.vala, src/RegexEntry.vala, src/Views/EditView.vala, src/Views/FilesView.vala
We need a little bit specified info on what these code does
=> Leave more comments

src/Views/EditView.vala, src/Views/FilesView.vala
Fixes #47
Also unify code struct between each view
=> Put views into each scrolled window

README.md, com.github.ryonakano.pinit.yml, meson.build, src/Application.vala
=> Use Adw.AboutWindow instead of Gtk.AboutDialog

src/AboutWindow.vala, src/Views/EditView.vala
A few grammatical changes meant to improve readability for English users.
=> English grammatical changes

src/Views/EditView.vala
=> EditView: Less strict on required keys

.editorconfig, data/gtk/help-overlay.ui, data/pinit.gresource.xml, meson.build, po/POTFILES, src/Application.vala, src/MainWindow.vala, src/Views/FilesView.vala
=> Add ShortcutsWindow and use ActionEntry for shortcut keys

data/meson.build
Originally from projects created by GNOME Builder
=> Add tests for metainfo

src/Backend/DesktopFileOperator.vala
=> DesktopFileOperator: Fix a regression that unlocalized Comment key no longer loaded

src/Backend/DesktopFileOperator.vala
Not an issue even if blank key exists but it's weird so remove if no longer used
=> DesktopFileOperator: Make sure to remove blank key

po/POTFILES, src/Model/DesktopFile.vala, src/Util/ExternalAppLauncher.vala, src/View/EditView.vala
- Improve error handling
- Remove unnecessary response handler for the error dialog
=> Improve open external

src/View/FilesView.vala
=> FilesView: Rename Preferences to Main Menu

meson.build, po/POTFILES, src/View/EditView.vala, src/Widget/CategoriesRow.vala
For consistency with the KeywordsRow added in #139
=> Rename CategoryChooser to CategoriesRow

src/MainWindow.vala
=> MainWindow: Fix unsaved dialog is shown after saving

src/MainWindow.vala, src/Model/DesktopFile.vala
=> MainWindow: Fix unsaved dialog is shown after saving (take 2)

src/Application.vala, src/Config.vala.in, src/MainWindow.vala
To disambiguate against Define namespace
=> Config: Rename namespace from Constants to Config

data/pinit.gschema.xml, src/Application.vala, src/Define.vala, src/View/FilesView.vala
This allows us to show the radiobutton in the corresponding GLib.Menu
=> Application: Use SimpleAction.stateful for styles

src/MainWindow.vala
Adw.ToastOverlay.add_toast() takes ownership of given toast
=> MainWindow: Create a instance of Adw.Toast every time when showing it

src/View/EditView.vala
Regression in 893b1985bb26e4b376f975e2cb995fd38d49cdfc
=> EditView: Fix missing Type key

src/View/EditView.vala
=> EditView: Add tooltip for each field

data/resources/pinit.gresource.xml.in, meson.build, po/POTFILES, src/Application.vala, src/Config.vala.in, src/MainWindow.vala, src/View/FilesView.vala, src/meson.build
Feedback from ryonakano/konbucase#159
- Change action name to "app.about"
- Show devel version
- Correct TRANSLATORS comment
=> feat: About dialog feedback from KonbuCase

build-aux/appcenter/com.github.ryonakano.pinit.Devel.yml, build-aux/flathub/com.github.ryonakano.pinit.Devel.yml, com.github.ryonakano.pinit.yml
Flatpak External Data Checker seems to force this style, which is annoying though, so switch to it now to avoid manifest update and coding style update from being in one commit
=> style: flatpak: Omit quote when possible

src/Model/DesktopFile.vala, src/Util/KeyFileUtil.vala, src/View/EditView.vala, src/meson.build
Some methods in DesktopFile are just wrappers of KeyFile and not related to DesktopFile itself.
=> Introduce KeyFileUtil

src/Model/DesktopFile.vala, src/View/EditView.vala
=> Support NoDisplay

data/pinit.metainfo.xml.in.in, meson.build
=> Release 2.2.0
