ryonakano/pinit

- com.github.ryonakano.pinit.yml
We can show the path in the home dir in this way but the path to else (e.g. on another disk) are still shown in the "/run" dir.
We should seek for another way to show the path correctly instead of giving unnecessary permission.
> Revert "Revert "Flatpak: Only allow access to the desktop files dir" (#65)"

- src/Backend/DesktopFileOperator.vala
- src/Views/EditView.vala
Changing the file mode to `700` can remove any permission to other users and it can be a problem when the given exec file is shared at e.g. on another disk, etc. We should just give exec permission to the file for the current user and keep the current file mode as same as possible.
> DesktopFilesOperator: Don't overwrite the current file mode

- data/pinit.metainfo.xml.in
- src/MainWindow.vala
- src/Views/FilesView.vala
Because it navigates back to the separator
> Fix navigate back shows empty window

- data/pinit.metainfo.xml.in
GNOME automatically excludes release descriptions on Damned Lies (GNOME Translation Platform). It's a good practice to follow the GNOME way.
This can streamline the translation process, allowing translators to focus their efforts on more critical and user-facing aspects of the application.
> data: Mark release descriptions as untranslatable

- com.github.ryonakano.pinit.yml
Fixes #113
Fixes #64
Fixes #61
While it it ideal to restrict filesystem permission, we've faced several issues due to this:
- Created desktop entries disappear after reboot/upgrade
- The path displayed in the entry is weird (/run/user/1000/...)
I thought making Pin It! copy the executable and icon files to ~/.local/share/applications where the desktop file is saved, because it would keep the filesystem permission as small as possible. However, it would need more considerations like the case when the size of the executable or icon file is huge (maybe we need some kind of the progress dialog...)
Considering these side effects, I think regaining access to HOME is simpler and better decision here.
> Flatpak: Regain access to HOME

- data/pinit.desktop.in
- data/pinit.metainfo.xml.in
- src/MainWindow.vala
Part of #123
```
ryo@b760m:~/work/ryonakano/pinit (shorten-app-summary)$ echo -n "Pin portable apps to the launcher" | wc -c
33
ryo@b760m:~/work/ryonakano/pinit (shorten-app-summary)$ 
```
> Make app summary shorter than 35 characters

- src/MainWindow.vala
It would be annoying if a user want to continue editing after that. Saving does not always mean completion of editing.
> MainWindow: Keep the view after saving

- src/View/EditView.vala
GenericName seems to be displayed in the app launcher on KDE.
> EditView: Allow setting GenericName

- src/MainWindow.vala
> MainWindow: Fix Esc in unsaved dialog discards changes and exits

- src/MainWindow.vala
Reverts ryonakano/pinit#141
This causes the issue that the unsaved dialog is never shown even modified after once saving, because this is a reference… 😵
> Revert "MainWindow: Fix unsaved dialog is shown after saving"

- src/Application.vala
We don't set any accel key for style previously and changing style works without this.
> Application: Remove useless reset accel key for style

- data/pinit.metainfo.xml.in
- Remove description about dropped feature
- Update caption text of screenshots
- "Edit view" sounds like to edit the view and ambiguous
- "execute permission" sounds more common than "execution permission"
> Metainfo: Update app descriptions

- src/View/EditView.vala
- src/Widget/CategoriesRow.vala
- src/Widget/KeywordsRow.vala
They're not intended to be used like: `notify["categories"]`
> Widgets: Use getter/setter methods instead of properties

- src/View/EditView.vala
For disambiguation with the desktop entries themselves.
> EditView: Do not use the word 'Entry' for each input widgets

- src/Model/DesktopFile.vala
- src/Model/DesktopFileModel.vala
- src/View/EditView.vala
- src/View/FilesView.vala
- Do not use one-word variable for searchability
- Add literal log message with error message for searchability
- Do not bundle multiple throws with one catch
> Improve error handling and logs

- src/MainWindow.vala
- src/View/EditView.vala
- src/View/FilesView.vala
We don't want to use MainWindow instance inside views other than the aim of setting transient window
> Use Gtk.Widget.get_root instead of keeping MainWindow instance

- .github/workflows/flatpak-x-checker.yml
Because the checker doesn't seem to accept multiple manifests:
```
[ryo@b760m ~/work/ryonakano/pinit (flatpak-x-checker-separate-steps)]$ flatpak run org.flathub.flatpak-external-data-checker --never-fork --edit-only ./build-aux/appcenter/com.github.ryonakano.pinit.Devel.yml  ./build-aux/flathub/com.github.ryonakano.pinit.Devel.yml  ./com.github.ryonakano.pinit.yml
usage: flatpak-external-data-checker [-h] [-v] [--update] [--commit-only] [--edit-only] [--check-outdated] [--filter-type {extra-data,file,archive,git}]
[--always-fork | --never-fork] [--unsafe] [--max-manifest-size MAX_MANIFEST_SIZE] [--require-important-update]
manifest
flatpak-external-data-checker: error: unrecognized arguments: ./build-aux/flathub/com.github.ryonakano.pinit.Devel.yml ./com.github.ryonakano.pinit.yml …
```
> chore: Actions: Separate steps per manifest

- src/MainWindow.vala
- src/Model/DesktopFile.vala
- src/Model/DesktopFileModel.vala
- src/View/EditView.vala
- src/View/FilesView.vala
MainWindow is not obliged to keep instances of unsaved DesktopFile and saved DesktopFile. We just compare only the KeyFile in DesktopFile anyways, so make DesktopFile do that job instead.
> Compare content of KeyFile in DesktopFile class & lessen disk access

- src/Model/DesktopFile.vala
- src/Util/KeyFileUtil.vala
Generics does not seem to support `string[]` so use GLib.Value instead.
```
../src/Model/DesktopFile.vala:140.63-140.70: error: Arrays are not supported as generic type arguments
140 |             string[]? categories = Util.KeyFileUtil.get_value<string[]> (keyfile_dirty, KeyFileDesktop.KEY_CATEGORIES, Util.KeyFileUtil.get_strv);
|                                                               ^~~~~~~~
../src/Model/DesktopFile.vala:154.40-154.47: error: Arrays are not supported as generic type arguments
154 |             Util.KeyFileUtil.set_value<string[]> (keyfile_dirty, KeyFileDesktop.KEY_CATEGORIES, categories, Util.KeyFileUtil.set_strv);
|                                        ^~~~~~~~
../src/Model/DesktopFile.vala:163.61-163.68: error: Arrays are not supported as generic type …
```
> KeyFileUtil: Generics with GLib.Value

- build-aux/appcenter/com.github.ryonakano.pinit.Devel.yml
- build-aux/flathub/com.github.ryonakano.pinit.Devel.yml
- com.github.ryonakano.pinit.yml
From https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html:
> Note, "app-id" is deprecated and preserved only for backwards compatibility.
> Flatpak: Use id instead of deprecated app-id
